### ISSUE TITLE
As a schoolteacher, I want my students to automatically be rewarded with default badges based on how long they have been active on CASMM and for the highest grades on specific assignments. (Default Badges) 3

### ISSUE THREAD

**Issue by matthewself12** [CEN3031-Group-7H/diamond-project16-7h#3]
Acceptance Criteria
- [ ] Teachers have pre-made badges that are automatically awarded to students from CASMM based on time student is enrolled

Tasks
- [ ] Familiarization and Planning
- [ ] Automatic badge assignment backend
- [ ] Create time-based badges

**Comment by ChandlerWiggins** [comment]
This user story is being eliminated because it is beyond the scope of this project. Badges will be assigned manually by teachers.
